# Generated by Django 3.2.9 on 2023-08-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectweight',
            name='grade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectweight',
            name='value',
            field=models.FloatField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
