# Generated by Django 3.2.9 on 2023-08-08 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_weight_course'),
        ('students', '0002_alter_studentsubject_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.responses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
