# Generated by Django 3.2.9 on 2023-07-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
