# Generated by Django 3.2.9 on 2023-07-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_weight_course'),
        ('students', '0005_studentweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=255)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.responses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
        ),
    ]
