# Generated by Django 4.2 on 2023-04-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.patterns')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.tags')),
            ],
        ),
    ]
