# Generated by Django 4.2 on 2023-04-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_tags_name_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='pattern',
        ),
    ]
