# Generated by Django 3.2.9 on 2023-07-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_responses_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('value', models.FloatField(max_length=255)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.responses')),
            ],
        ),
    ]
