# Generated by Django 3.2.9 on 2023-07-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('chatbot', '0004_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
